require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'SimpleBLEGlucoseReader' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enaSimpleBLEGlucoseReader hermes on iOS, change `false` to `true` and then install pods
    :hermes_enaSimpleBLEGlucoseReaderd => flags[:hermes_enaSimpleBLEGlucoseReaderd],
    :fabric_enaSimpleBLEGlucoseReaderd => flags[:fabric_enaSimpleBLEGlucoseReaderd],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'SimpleBLEGlucoseReaderTests' do
    inherit! :complete
    # Pods for testing
  end

  # EnaSimpleBLEGlucoseReaders Flipper.
  #
  # Note that if you have use_frameworks! enaSimpleBLEGlucoseReaderd, Flipper will not work and
  # you should disaSimpleBLEGlucoseReader the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
